sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: hhvm
env:
  - SYMFONY="2.7.*"
  - SYMFONY="~3.0"
services:
  - elasticsearch
install:
  - composer require --no-update symfony/symfony:${SYMFONY}
before_script:
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - composer install --no-interaction --prefer-dist
script:
  - vendor/bin/phpunit --coverage-clover=coveralls.clover
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/,Tests/app/ ./
after_script:
  - vendor/bin/coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/81e47479feba5ba8dc47
    on_success: change
    on_start: never
